config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update] do
      get "orders" => "customers#orders"
    end

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, except: [:destroy]

    resources :orders, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    get "search" => "searches#search"
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get :search, on: :collection
    end

    resource :customer, only: [:show, :edit, :update]
    get 'customers/quit', as: 'quit'
    patch 'customers/withdraw', as: 'withdraw'

    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]

    delete 'cart_items/empty', as: 'empty'
    resources :cart_items, only: [:index, :create, :update, :destroy]


    get 'orders/completed', as: 'completed'
    post 'orders/confirmation', as: 'confirmation'
    resources :orders, only: [:new, :create, :index, :show]

    get 'search' => 'searches#search'
  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :shipping_addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true, length: {maximum: 7}
  validates :address, presence: true
  validates :telephone_number, presence: true, length: {maximum: 11}
  
  def self.looks(search, word)
    if search == "完全一致"
      @customer = Customer.where("family_name_kana LIKE?", "#{word}")
    elsif search == "曖昧検索"
      @customer = Customer.where("family_name_kana LIKE?", "%#{word}%")
    else
      @customer = Customer.all
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
    @customer_name = @customer.family_name + @customer.first_name
  end

  def update
    @customer =Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報を更新しました。"
    else
      #名前をブランクで更新した場合、名前が表示されなくなるため、一度、会員情報を引き出し、変数に設定した。
      customer =Customer.find(params[:id])
      @customer_name = customer.family_name + customer.first_name
      render "edit"
    end
  end

  def orders
    @customer = Customer.find(params[:customer_id])
    @customer_name = @customer.family_name + @customer.first_name
    @orders = @customer.orders.order("order_status ASC").page(params[:page]).per(15)
  end

  private

  def customer_params
    params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_customer_edit.html.erb
<div class="form-group-row">
  <%= f.label :氏名, class:"col-2" %>
  <%= f.text_field :family_name, autofocus: true, class:"mr-5" %>
  <%= f.text_field :first_name %>
</div>
<div class="form-group-row">
  <%= f.label :フリガナ, class:"col-2" %>
  <%= f.text_field :family_name_kana, class:"mr-5" %>
  <%= f.text_field :first_name_kana %>
</div>
<div class="form-group-row">
  <%= f.label :郵便番号, class:"col-2" %>
  <%= f.text_field :postal_code %>
</div>
<div class="form-group-row">
  <%= f.label :住所, class:"col-2" %>
  <%= f.text_field :address, class: "col-9" %>
</div>
<div class="form-group-row">
  <%= f.label :電話番号, class:"col-2" %>
  <%= f.text_field :telephone_number %>
</div>
<div class="form-group-row">
  <%= f.label :メールアドレス, class:"col-2" %>
  <%= f.text_field :email %>
</div>

app/views/admin/customers/edit.html.erb
<%= render 'layouts/error_messages', model: @customer %>

<div class="container">
  <h3 class="bg-light orange d-inline-block px-4 mx-5 mb-3"><i class="fas fa-user dark-brown"></i> <%= @customer_name %>さんの会員情報編集</h3>

  <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>

  <div class="form-group-row d-flex">
    <div class="col-2">会員ID</div>
    <%= @customer.id %>
  </div>

  <%= render "customer_edit", f: f %>

  <div class="form_group-row">
    <%= f.label :会員ステータス, class: "col-2" %>
    <%= f.radio_button :is_deleted, false %>
    <%= f.label :is_deleted, "有効", class: "mr-3" %>
    <%= f.radio_button :is_deleted, true %>
    <%= f.label :is_deleted, "退会" %>
  </div>

  <div class="form-group-row d-flex">
    <div class="col-2"></div>
    <%= f.submit "変更を保存", class: "btn bg-orange-dark col-2" %>
  </div>



  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h3 class="bg-light orange d-inline-block px-4 mx-5 mb-3"><i class="fas fa-users dark-brown"></i> 会員一覧</h3>

  <table class="table table-hover">
    <thead class="bg-light-brown">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
         <td><%= customer.id %></td>
         <td>
           <%= link_to admin_customer_path(customer.id) do %>
             <%= customer.family_name %><%= customer.first_name %>
           <% end %>
         </td>
         <td><%= customer.email %></td>
         <% if customer.is_deleted == false %>
            <td class="text-success"><strong>有効</strong></td>
         <% else %>
            <td class="text-black-50"><strong>退会</strong></td>
         <% end %>
      </tr>
      <% end %>
    </tbody>

  </table>
  <div class="paginate d-flex justify-content-center">
      <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/orders.html.erb
<div class="container">
  <h3 class="bg-light orange d-inline-block px-4 mx-5 mb-3"><i class="fas fa-shopping-cart dark-brown"></i> <%= @customer_name %>さんの注文履歴一覧</h3>

  <div class="container row justify-content-center">
    <table class="table">
      <thead class="bg-light-brown">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
          <td><%= order.customer.family_name + order.customer.first_name %>
          <td><%= order.total %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h3 class="bg-light orange d-inline-block px-4 mx-5 mb-3"><i class="fas fa-user dark-brown"></i> <%= @customer.family_name %><%= @customer.first_name %>さんの会員詳細</h3>

  <table class="my-3">
    <tr>
      <th style="height: 50px; width: 200px;">会員ID</th>
      <th><%= @customer.id %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">氏名</th>
      <th><%= @customer.family_name %>　<%= @customer.first_name %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">フリガナ</th>
      <th><%= @customer.family_name_kana %>　<%= @customer.first_name_kana %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">郵便番号</th>
      <th><%= @customer.postal_code %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">住所</th>
      <th><%= @customer.address %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">電話番号</th>
      <th><%= @customer.telephone_number %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">メールアドレス</th>
      <th><%= @customer.email %></th>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;">会員ステータス</th>
      <% if @customer.is_deleted == false %>
        <th class="text-success"><strong>有効</strong></th>
      <% else %>
        <th class="text-black-50"><strong>退会</strong></th>
      <% end %>
    </tr>
    <tr>
      <th style="height: 50px; width: 200px;"></th>
      <th>
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn bg-orange-dark mr-5" %>
        <%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customer), class: "btn bg-dark-brown" %>
      </th>
    </tr>
  </table>


</div>