config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update] do
      get "orders" => "customers#orders"
    end

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, except: [:destroy]

    resources :orders, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    get "search" => "searches#search"
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only: [:index, :show] do
      get :search, on: :collection
    end

    resource :customer, only: [:show, :edit, :update]
    get 'customers/quit', as: 'quit'
    patch 'customers/withdraw', as: 'withdraw'

    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]

    delete 'cart_items/empty', as: 'empty'
    resources :cart_items, only: [:index, :create, :update, :destroy]


    get 'orders/completed', as: 'completed'
    post 'orders/confirmation', as: 'confirmation'
    resources :orders, only: [:new, :create, :index, :show]

    get 'search' => 'searches#search'
  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% if notice %>
<div class="bg-light-brown"><%= notice %></div><% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <div class="navbar-brand">
      <div class="py-1">
        <%= link_to root_path do %>
          <%= image_tag "nagano_logo.jpg", size: "300x60" %>
        <% end %>
      </div>
    </div>

    <% if customer_signed_in? %>
      <div class="center">
        <p>ようこそ、<%= customer.family_name %>さん！</p>
      </div>
    <% end %>

    <div class="d-flex align-items-end justify-content-center flex-column bd-highlight mb-3 mt-2" style="height: 80px;">
      <ul class="navbar-nav mt-2">
        <% if customer_signed_in? %>
          <li class="nav-link">
            <%= link_to customer_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-user"></i> マイページ
            <% end %>
          </li>

          <li class="nav-link ml-3">
            <%= link_to items_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-cookie-bite"></i> 商品一覧
            <% end %>
          </li>

          <li class="nav-link ml-3">
            <%= link_to cart_items_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-shopping-cart"></i> カート
            <% end %>
          </li>

          <li class="nav-link ml-3">
            <%= link_to destroy_customer_session_path, method: :delete, class:"btn bg-dark-brown" do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>

        <% elsif admin_signed_in? %>

          <li class="nav-link">
            <%= link_to admin_items_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-cookie-bite"></i> 商品一覧
            <% end %>
          </li>

          <li class="nav-link">
            <%= link_to admin_customers_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-users"></i> 会員一覧
            <% end %>
          </li>

          <li class="nav-link">
            <%= link_to admin_orders_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-shopping-cart"></i> 注文履歴一覧
            <% end %>
          </li>

          <li class="nav-link">
            <%= link_to admin_genres_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-cookie-bite"></i> ジャンル一覧
            <% end %>
          </li>

          <li class="nav-link">
            <%= link_to destroy_admin_session_path, method: :delete, class:"btn bg-dark-brown" do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>

        <% else %>

          <li class="nav-link">
            <%= link_to about_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-truck"></i> About
            <% end %>
          </li>

        <li class="nav-link ml-3">
          <%= link_to items_path, class:"btn bg-dark-brown" do %>
            <i class="fas fa-cookie-bite"></i> 商品一覧
          <% end %>

          <li class="nav-link ml-3">
            <%= link_to new_customer_registration_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>

          <li class="nav-link ml-3">
            <%= link_to new_customer_session_path, class:"btn bg-dark-brown" do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>

      <div class="search_form my-2">
        <% if admin_signed_in? %>
          <%= form_with method: :get, url: admin_search_path do |f| %>
            <div class="d-flex">
              <div class="p-1">
                <%= f.select :search, options_for_select([["完全一致"], ["曖昧検索"]]) %>
                <%= f.select :range, options_for_select([["商品"], ["会員(姓カナ)"],["ジャンル"]]) %>
              </div>
              <div class="border p-1">
                <%= f.text_field :word, placeholder: "Search", style: "border: 0; outline: 0;" %>
                <%= f.button :type => "submit", style: "border-style: none; background: none;" do %>
                  <i class="fas fa-search"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= form_with method: :get, url: search_path do |f| %>
            <%= f.hidden_field :range, :value => "商品" %>
            <%= f.hidden_field :search, :value => "曖昧検索" %>
            <div class="border p-1">
              <%= f.text_field :word, placeholder: "Search", style: "border: 0; outline: 0;" %>
              <%= f.button :type => "submit", style: "border-style: none; background: none;" do %>
                <i class="fas fa-search"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5/css/bootstrap.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/header", customer: current_customer %>
    </header>
    <main class="pb-5">
      <div class="text-center" style="height:30px;">
        <div id="flash-message" style="display:none;">
          <%= render "layouts/flash_message" %>
        </div>
      </div>
      <%= yield %>
    </main>
    <footer class="text-center fixed-bottom brown mt-3 pt-1" style="height: 40px"><small>ながのCAKE</small>
    </footer>
  </body>
</html>